### ISSUE TITLE
Talents. Stats and Images

### ISSUE THREAD

**Issue by alessandrodias** [samidhdk/Warcraft-Rumble-RESTful-API#1]
First of all, congratulations for this! I was looking for this "api" and finally found your repository!

Do you know this site https://arclightbase.com? I think it's a good source to get complete informations and improve the json you created with stats and talents data, and besides, you can even get the images from there.

**Comment by samidhdk** [comment]
Thank you very much, Alessandro, for your kind words.

What you said is a great idea. Adding talents and base stats is something I'll be working on in the following days.

I'll also consider the images proposal!

**Comment by samidhdk** [comment]
talents and base stats added!
